### PR TITLE
Joss

### PR DESCRIPTION
**Pull request by fdelesma**
This manuscript update contains important changes due to rewriting and comments by P. Rinke . These changes are also due to the response to Rinke's comments and the review by  D. Golze , J. Wilhelm and F. Delesma.  The description of low scaling algorithms was added in Figure 1 . The inputs and outputs of GreenX was added in Table 1.

### CODE REVIEW

**Comment by JWilhelm** [comment]
Thank you for uploading the changes here. A few points that might be considered: 

1) Would it be possible to move Dorothea's Figure 1 to the top? Would it be also possible to include a PDF of Figure 1 instead of the png? In case a PDF is not possible, is it possible to improve the resolution of the png substantially? 

2) I couldn't produce a PDF of the current version. In the older version 

https://github.com/nomad-coe/greenX/actions/runs/5005903193

there were still some '(??)' from wrong references. Is it possible to check in a more recent PDF whether the wrong references are fixed? 

3) The formatting of Table 1 could be improved. In the older version

https://github.com/nomad-coe/greenX/actions/runs/5005903193

there is a lot of white space in the first column. Ideally, every output grid will fit in a single line.

**Review by dgolze — COMMENTED** [review]
- I noticed that some changes in the equation didn't make it to the JOSS, I fixed it
- the picture is has good quality in the pdf I downloaded

**Review by aziziph — APPROVED** [review]
It seems OK to Xavier and I. Thank you!

**Review by dgolze — APPROVED** [review]
I am ok with the changes. @aziziph In the references, the style how for the journal names should be the same. Same are abbreviated and some are not. Usually, one would use the abbreviations for all of them. Can you take care of this?

**Pull request merged**
