### PR TITLE
Pages only considers subtrees

### PR DESCRIPTION
**Pull request by Panadestein**
Another iteration on the GH pages

### CODE REVIEW

**Review by dgolze — APPROVED** [review]
and here we go again

**Comment by fdelesma** [comment]
I was thinking to try the full path of the readme:

https://github.com/nomad-coe/greenX/blob/main/GX-TimeFrequency/README.md

**Comment by Panadestein** [comment]
I read that it will only render files in the current's directory subtree

**Review by fdelesma — APPROVED** [review]
Let's go!

**Pull request merged**
